export const ADDRESS_TYPE = {
    HOME: "HOME",
    OFFICE: "OFFICE",
    SHOP: "SHOP",
    OTHER: "OTHER",
    HOSTEL: "HOSTEL",
    ORIGIN: "ORIGIN",
    VENDOR: "VENDOR",
    PICKUP: "PICKUP",
};

export const ADDRESS_TYPE_LIST = [
    ADDRESS_TYPE.HOME,
    ADDRESS_TYPE.OFFICE,
    ADDRESS_TYPE.SHOP,
    ADDRESS_TYPE.OTHER,
    ADDRESS_TYPE.HOSTEL,
    ADDRESS_TYPE.ORIGIN,
    ADDRESS_TYPE.VENDOR,
    ADDRESS_TYPE.PICKUP,
];
