export const STATUS_FOR = {
    ORDER: "ORDER",
    PRODUCT: "PRODUCT",
    PRODUCT_CATEGORY: "PRODUCT_CATEGORY",
    USER: "USER",
    PAYMENT_STATUS: "PAYMENT_STATUS",
    DELIVERY_STATUS: "DELIVERY_STATUS",
    REFUND_STATUS: "REFUND_STATUS",
};

export const STATUS_FOR_LIST = [
    STATUS_FOR.ORDER,
    STATUS_FOR.PRODUCT,
    STATUS_FOR.PRODUCT_CATEGORY,
    STATUS_FOR.USER,
    STATUS_FOR.PAYMENT_STATUS,
    STATUS_FOR.DELIVERY_STATUS,
    STATUS_FOR.REFUND_STATUS,
];
