// PRODUCT_STATUS
const PRODUCT_STATUS = {
    ACTIVE: "ACTIVE",
    COMING_SOON: "COMING_SOON",
    SOLD_OUT: "SOLD_OUT",
    OUT_OF_STOCK: "OUT_OF_STOCK",
    DELETED: "DELETED",
    INACTIVE: "INACTIVE",
    DISCONTINUED: "DISCONTINUED",
    APPROVAL_PENDING: "APPROVAL_PENDING",
};

const PRODUCT_STATUS_ARRAY = [
    PRODUCT_STATUS.ACTIVE,
    PRODUCT_STATUS.INACTIVE,
    PRODUCT_STATUS.DELETED,
    PRODUCT_STATUS.OUT_OF_STOCK,
    PRODUCT_STATUS.COMING_SOON,
    PRODUCT_STATUS.SOLD_OUT,
    PRODUCT_STATUS.DISCONTINUED,
    PRODUCT_STATUS.APPROVAL_PENDING,
];

// ----------------------------------------

const PRODUCT_FEATURED_IN = {
    BEST_SELLER: "BEST_SELLER",
    NEW_ARRIVAL: "NEW_ARRIVAL",
    TOP_RATED: "TOP_RATED",
    RECOMMENDED: "RECOMMENDED",
    TRENDING: "TRENDING",
    MOST_VIEWED: "MOST_VIEWED",
    COMING_SOON: "COMING_SOON",
    FEATURED: "FEATURED",
    ON_SALE: "ON_SALE",
    NORMAL: "NORMAL",
};

const PRODUCT_FEATURED_IN_ARRAY = [
    PRODUCT_FEATURED_IN.BEST_SELLER,
    PRODUCT_FEATURED_IN.NEW_ARRIVAL,
    PRODUCT_FEATURED_IN.TOP_RATED,
    PRODUCT_FEATURED_IN.RECOMMENDED,
    PRODUCT_FEATURED_IN.TRENDING,
    PRODUCT_FEATURED_IN.MOST_VIEWED,
    PRODUCT_FEATURED_IN.COMING_SOON,
    PRODUCT_FEATURED_IN.FEATURED,
    PRODUCT_FEATURED_IN.ON_SALE,
    PRODUCT_FEATURED_IN.NORMAL,
];

const PUBLIC_ALLOWED_PRODUCT_STATUS = [
    PRODUCT_STATUS.ACTIVE,
    PRODUCT_STATUS.COMING_SOON,
    PRODUCT_STATUS.SOLD_OUT,
];

const PRODUCT_ENUMS = {
    PRODUCT_STATUS,
    PRODUCT_STATUS_ARRAY,
    PRODUCT_FEATURED_IN,
    PRODUCT_FEATURED_IN_ARRAY,
    PUBLIC_ALLOWED_PRODUCT_STATUS,
};

export default PRODUCT_ENUMS;
